##
#  CMakeLists.txt
#
#  Copyright (C) 2025-2025 srcML, LLC. (www.srcDiff.org)
#
#  This file is part of the srcDiffDispatch.
#
#  The srcDiffDispatch is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  The srcDiffDispatch is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with the srcDiffDispatch; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

cmake_minimum_required(VERSION 3.14)
project(srcDispatch)

include(CTest)

if(NOT WIN32)
    set(CMAKE_INSTALL_PREFIX "/usr/local/")
endif()

set(CMAKE_POSITION_INDEPENDENT_CODE ON)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_definitions("-Wall")

add_subdirectory(srcDispatch/CMake)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)

set(SRCDIFF_DISPATCH_INCLUDE_DIR ${SRCSAX_INCLUDE_DIR}
                         src/policy_classes
                         src/dispatcher
    CACHE INTERNAL "Include directories for srcDispatch")

set(SRCDIFF_DISPATCH_LIBRARIES ${SRCSAX_LIBRARIES} CACHE INTERNAL "Libraries for srcDiffDispatch")

# include needed includes
include_directories(${SRCDIFF_DISPATCH_INCLUDE_DIR})

# Continue to src
add_subdirectory(src)
add_subdirectory(test)
